---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-volume
  namespace: media
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-volume
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual