---
apiVersion: v1
kind: Service
metadata:
  name: youtube-downloader-web
  namespace: media
spec:
  selector:
    app: youtube-downloader-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: youtube-downloader-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-downloader-web
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-downloader-web
  template:
    metadata:
      labels:
        app: youtube-downloader-web
    spec:
      containers:
        - name: youtube-downloader-web
          image: alexta69/metube:2023-02-28
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: UID
              value: "1001"
            - name: GID
              value: "1001"
          volumeMounts:
            - name: downloads-volume
              mountPath: /downloads
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
      volumes:
        - name: downloads-volume
          hostPath:
            path: ${MEDIA_BASE_DIRECTORY}/YouTube