---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: geck
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
      name: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: geck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2023.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8123
              protocol: TCP
          env:
            - name: TZ
              value: "${TIMEZONE}"
          volumeMounts:
            - name: home-assistant-config-volume
              mountPath: /config
            - name: home-assistant-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
      volumes:
        - name: home-assistant-config-volume
          hostPath:
            path: ${HOMEASSISTANT_BASE_DIRECTORY}/config
        - name: home-assistant-config
          configMap:
            name: home-assistant-config-map
            items:
            - key: configuration.yaml
              path: configuration.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-map
  namespace: geck
data:
  configuration.yaml: |
    default_config:

    http:
      server_port: 8123
      use_x_forwarded_for: true
      trusted_proxies:
        - !env_var PROXY_SERVER_IP
      ip_ban_enabled: true
      login_attempts_threshold: 5

    tts:
      - platform: google_translate