---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: geck
spec:
  selector:
    app: plex
  type: NodePort
  ports:
    - port: 32400
      targetPort: 32400
      name: plex-web
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: plex-dlna-tcp
      protocol: TCP
    - port: 1900
      targetPort: 1900
      name: plex-dlna-udp
      protocol: UDP
    - port: 5353
      targetPort: 5353
      name: plex-discovery-udp
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: geck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: linuxserver/plex:1.31.1
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 32400 #PMS
            name: plex
          - containerPort: 32400
            name: plex-udp
            protocol: UDP
          - containerPort: 32469 #Plex DLNA
            name: plex-dlna
          - containerPort: 5353
            name: plex-discovery
            protocol: UDP
          - containerPort: 1900 #Plex DLNA
            name: plex-dlna-udp
            protocol: UDP
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "${TIMEZONE}"
            - name: PLEX_CLAIM
              value: "${PLEX_CLAIM_TOKEN}"
            - name: HOSTNAME
              value: plex.geck.svc.cluster.local
          volumeMounts:
            - name: plex-config-volume
              mountPath: /config
            - name: plex-transcode-volume
              mountPath: /transcode
            - name: media-volume
              mountPath: /data
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: plex-config-volume
          hostPath:
            path: ${PLEX_BASE_DIRECTORY}/config
        - name: plex-transcode-volume
          hostPath:
            path: ${PLEX_BASE_DIRECTORY}/transcode
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc-volume