---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: common
    - role: k3s/download

- hosts: master
  become: yes
  roles:
    - role: k3s/common
    - role: k3s/master
    - role: geck

- hosts: lab_computer_1
  become: yes
  roles:
    - role: k3s/common
    - role: k3s/node
    - role: raspberrypi
