---
- include_tasks: backups.yml
- include_tasks: media.yml

- name: Create programs base directory
  ansible.builtin.file:
    path: '/opt/{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - programs
    - scripts

- name: Copy homer assets
  ansible.builtin.copy:
    src: logo.webp
    dest: /opt/programs/homer-web/www/images

- name: Increase UDP buffer size
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: "2500000"
    state: present
    reload: yes